### ISSUE TITLE
Release new version of GHG dashboard

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/veda-config-ghg#465]
# TODO
- [x] Publish LPJeosim to production
- [x] NOAA interface staging -> production
- [x] ghgc-docs staging -> production (so the URLs are available)
- [x] Bump version GHG
- [x] Test
